#!/bin/bash
#1: Missing file $LIST
IPT="/sbin/iptables"
LIST="/root/lists/full_access"
CT="/bin/cat"
GM="/root/scripts/gathermacs"
GR="/bin/grep"

#Test for list file existance
if [ ! -f "$LIST" ];then
				echo "Missing file $FILE";
				exit 1;
fi

#Create chains
echo "Clearing chains"
$IPT -F accounting_out -t mangle &>/dev/null
$IPT -F accounting_in -t mangle &>/dev/null

#Add new chains to built in chains
echo "Unhooking from standard chains"
$IPT -D PREROUTING -t mangle -j accounting_in &> /dev/null
$IPT -D POSTROUTING -t mangle -j accounting_out &> /dev/null
