#!/bin/bash
#1:Missing ports file
SOURCE="/root/scripts/scriptheader"
[ -f "$SOURCE" ] && . "$SOURCE"

GROUP_TABLE="user_groups"
TRAFFIC_TABLE="traffic"
LIMIT=64000
MAC_TABLE="macs"
GR="/bin/grep"
PORTS_FILE="/root/scripts/port_groups"
IPT="/sbin/iptables"
LIST="/root/lists/full_access"
CT="/bin/cat"
GM="/root/scripts/gathermacs"
GR="/bin/grep"
[ ! -f "$PORTS_FILE" ] && echo "Missing $PORTS_FILE" && exit 1
