#!/bin/bash

#Load defaults
HEADER="/root/scripts/scriptheader"
if [ -f "$HEADER" ];then
	. "$HEADER"
else
	echo "Missing file ($HEADER). Stopping."
	exit 1;
fi

###
#Override variables here
###
FOUND_SECTION=0;

###
#Declare functions here
###

###
#Main script start
###

##Test parameters
if [ "$1" == "" ];then
	$EC "Missing parameter"
	$EC "Use: $(basename $0) <hostname>"
	exit 1;
fi

MAC=`$GM mac $1`
if [ "$MAC" == "" ];then
	COUNT=`$GM find $1|$WC -l`
	if [ $COUNT -gt 0 ];then
		$EC $EC_PARM "${S_WARN}Unable to get mac from DB. These are your options:${R}"
		$GM find $1
		exit 2;
	else
		MAC=`$GM find $1|$AW '{print $6}'`
		$EC $MAC|$GR -i "..:..:..:..:..:.." > /dev/null
		if [ $? -ne 0 ];then
			$EC $EC_PARM "${S_WARN}Unable to get mac from DB. These are your options:${R}"
			if [ $COUNT -gt 0 ];then
				$GM find $1
				exit 2;
			else
				$EC $EC_PARM "\t**None**"
				exit 2;
			fi
		fi
	fi
fi

if [ ! -f "$DHCP_CONFFILE" ];then
	exit 3;
fi

if [ -f "$CLASSFILE" ];then
	CLASS=`$GR -i $MAC $CLASSFILE|$AW '{print $2}'`
else
	$EC $EC_PARM "${S_ERR}Missing file ($CLASSFILE)${R}"
	exit 4;
fi

if [ "$CLASS" == "" ];then
	$EC "Host not in class file!"
	exit 5;
else
	while read line;do
		$EC $line | $GR "#" &> /dev/null
		if [ $? -eq 0 ];then
			continue;
		fi
		$EC $line|$GR "allow members of $CLASS" > /dev/null
		if [ $? -eq 0 ];then
			FOUND_SECTION=1;
			continue;
		else
			if [ $FOUND_SECTION -eq 0 ];then
				continue;
			fi
		fi

		if [ $FOUND_SECTION -eq 1 ];then
			$EC $line|$GR "router"|$AW '{print $3}'|$SD -e 's/;//'
		fi;

		$EC $line|$GR "\}" > /dev/null
		if [ $? -eq 0 ] && [ $FOUND_SECTION -eq 1 ];then
			exit 0;
		fi
	done < "$DHCP_CONFFILE"
fi
